---
title: "Authorship"
---

## Data are public, and harmonizing them into something meaningful is hard
Data collected as part of NSF funded networks and observatories (LTER, CZO, and NEON) are intended to be publically available.  Much of this legacy data, however, has been collected and archived in ways that preclude meaningful cross site synthesis.  The major objective of this working group, is to collate and harmonize these datasets in a scripted, tractable manner.  

Many of the raw datasets collected for the database have already been published and archived in Electronic data interchange (EDI) , or other data repositories.  In some cases, data from unpublished sources have been included in the database (with permission of the data generators). For both published and unpublished data, personal knowledge about the individual sites and experiments are critical for accurately understanding the data products and linking across datasets.  The willingness of many scientists to cooperate and collaborate is what makes this synthesis possible. We have attempted to lay out ground rules to establish a fair process for establishing authorship, and to be inclusive while not diluting the value of authorship on a manuscript. 

Our primary goals in the authorship process are to consistently, accurately and transparently attribute the contribution of each author on the paper, to encourage participation in manuscripts by interested scientists, and to ensure that each author has made sufficient contribution to the paper to warrant authorship. Towards this end we have developed authorship guidelines for both the initial database paper and subsequent scientific papers that use the database. _Please note, physical attendance at any of our meeting is not a requirement._

