---
title: "QC_plots"
output: html_document
---

```{r README, eval=FALSE, echo=FALSE}

# This workflow harvests html files generated from the
# soilHarmonization::homogenization_QC(), copies those html files from Aurora to
# the docs/qaqc folder of the lterwg-som GitHub repository, and generates
# references to those files as hyperlinks on the QC_plots tab of the project
# website (https://lter.github.io/lterwg-som/index.html).

# Pivotal to this workflow is the transfer of homogenization output, including
# the html files from Google Drive to the docs/qaqc folder in the project
# repository. This transfer is necessary as the google_drive package is unable
# to read html files directly from Google Drive. At this time, the transfer of
# files/output from Google Drive to the Data-downloads folder on Aurora
# (/home/shares/lter-som/Data-downloads) is a bash process facilitated with
# Rclone (see below).

# rclone sync ltersom:LTER-SOM/Data_downloads Data-downloads
```


```{r library, echo=FALSE, include=FALSE}

library(tools)
library(tidyverse)
library(kableExtra)
```


```{r GD_to_GH, echo=FALSE, include=FALSE}

file.copy(from = list.files(path = '/home/shares/lter-som/Data-downloads/',
                            full.names = TRUE,
                            pattern = "*_HMGZD_QC.html",
                            recursive = TRUE),
          to = '/home/earl/localRepos/lterwg-som/docs/qaqc/',
          overwrite = TRUE,
          recursive = FALSE)
```


```{r list_of_links, echo=FALSE}

# target format
# [Stacy_2015_ssCZO_Bull_HMGZD_QC](qaqc/Stacy_2015_ssCZO_Bull_HMGZD_QC.html) 

qaqcFileList <- tibble(
  qaqcFileList = list.files(path = '/home/earl/localRepos/lterwg-som/docs/qaqc/',
                            full.names = FALSE,
                            recursive = FALSE),
  qaqcFileListSansExt = file_path_sans_ext(qaqcFileList)
) %>% 
  mutate(file_list = paste0('[', qaqcFileListSansExt, '](qaqc/', qaqcFileList, ')')) %>% 
  select(file_list) 
```


```{r output_links, results='asis', echo=FALSE}

knitr::kable(qaqcFileList)
```
